In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [3]:
import numpy as np
import pandas as pd

In [19]:
pd.read_csv('gdrive/My Drive/Colab Notebooks/Air_Quality.csv')

,Unique ID,Indicator ID,Name,Measure,Measure Info,Geo Type Name,Geo Join ID,Geo Place Name,Time Period,Start_Date,Data Value,Message
0,172653,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2011,12/01/2010,25.30,NaN
1,172585,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2009,12/01/2008,26.93,NaN
2,336637,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,204,East New York,Annual Average 2015,01/01/2015,19.09,NaN
3,336622,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,103,Fordham - Bronx Pk,Annual Average 2015,01/01/2015,19.76,NaN
4,172582,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,104,Pelham - Throgs Neck,Annual Average 2009,12/01/2008,22.83,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
16213,130750,647,Outdoor Air Toxics - Formaldehyde,Annual average concentration,µg/m3,UHF42,211,Williamsburg - Bushwick,2005,01/01/2005,3.10,NaN
16214,130780,647,Outdoor Air Toxics - Formaldehyde,Annual average concentration,µg/m3,Borough,5,Staten Island,2005,01/01/2005,2.30,NaN
16215,131020,652,Cardiac and respiratory deaths due to Ozone,Estimated annual rate,"per 100,000",UHF42,504,South Beach - Tottenville,2005-2007,01/01/2005,7.50,NaN
16216,131026,652,Cardiac and respiratory deaths due to Ozone,Estimated annual rate,"per 100,000",Borough,5,Staten Island,2005-2007,01/01/2005,7.80,NaN
16217,325247,643,Annual vehicle miles traveled,million miles,per km2,CD,107,Upper West Side (CD7),2016,01/01/2016,50.00,NaN

In [5]:
AirData = pd.read_csv('gdrive/My Drive/Colab Notebooks/Air_Quality.csv')

In [8]:
AirData.columns

Index(['Unique ID', 'Indicator ID', 'Name', 'Measure', 'Measure Info',
       'Geo Type Name', 'Geo Join ID', 'Geo Place Name', 'Time Period',
       'Start_Date', 'Data Value', 'Message'],
      dtype='object')

In [9]:
AirData.dtypes

Unique ID           int64
Indicator ID        int64
Name               object
Measure            object
Measure Info       object
Geo Type Name      object
Geo Join ID         int64
Geo Place Name     object
Time Period        object
Start_Date         object
Data Value        float64
Message           float64
dtype: object

In [22]:
AirData.Name.value_counts()

Name
Nitrogen dioxide (NO2)                                    5499
Fine particles (PM 2.5)                                   5499
Ozone (O3)                                                1974
Asthma emergency department visits due to PM2.5            384
Asthma hospitalizations due to Ozone                       384
Asthma emergency departments visits due to Ozone           384
Annual vehicle miles travelled (cars)                      214
Annual vehicle miles travelled (trucks)                    209
Annual vehicle miles traveled                              209
Outdoor Air Toxics - Benzene                               203
Outdoor Air Toxics - Formaldehyde                          203
Cardiac and respiratory deaths due to Ozone                192
Deaths due to PM2.5                                        192
Cardiovascular hospitalizations due to PM2.5 (age 40+)     192
Respiratory hospitalizations due to PM2.5 (age 20+)        192
Boiler Emissions- Total NOx Emissions                       96
Boiler Emissions- Total SO2 Emissions                       96
Boiler Emissions- Total PM2.5 Emissions                     96
Name: count, dtype: int64

In [20]:
NO2_Subset = AirData[AirData["Name"] == "Nitrogen dioxide (NO2)"].copy()

In [26]:
NO2_Subset

,Unique ID,Indicator ID,Name,Measure,Measure Info,Geo Type Name,Geo Join ID,Geo Place Name,Time Period,Start_Date,Data Value,Message
0,172653,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2011,12/01/2010,25.30,NaN
1,172585,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,203,Bedford Stuyvesant - Crown Heights,Annual Average 2009,12/01/2008,26.93,NaN
2,336637,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,204,East New York,Annual Average 2015,01/01/2015,19.09,NaN
3,336622,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,103,Fordham - Bronx Pk,Annual Average 2015,01/01/2015,19.76,NaN
4,172582,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,104,Pelham - Throgs Neck,Annual Average 2009,12/01/2008,22.83,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
16206,643315,375,Nitrogen dioxide (NO2),Mean,ppb,Borough,5,Staten Island,Annual Average 2019,01/01/2019,11.92,NaN
16207,179272,375,Nitrogen dioxide (NO2),Mean,ppb,Borough,5,Staten Island,Winter 2008-09,12/01/2008,21.63,NaN
16208,602701,375,Nitrogen dioxide (NO2),Mean,ppb,Borough,5,Staten Island,Winter 2017-18,12/01/2017,18.92,NaN
16210,171567,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,205,Sunset Park,Winter 2008-09,12/01/2008,30.17,NaN
16211,211560,375,Nitrogen dioxide (NO2),Mean,ppb,UHF34,205,Sunset Park,Winter 2013-14,12/01/2013,27.68,NaN

In [29]:
O3_Subset = AirData[AirData["Name"] == "Ozone (O3)"].copy()

In [30]:
PM_Subset = AirData[AirData["Name"] == "Fine particles (PM 2.5)"].copy()

In [31]:
Benzene_Subset = AirData[AirData["Name"] == "Outdoor Air Toxics - Benzene"].copy()

In [32]:
Formaldehyde_Subset = AirData[AirData["Name"] == "Outdoor Air Toxics - Formaldehyde"].copy()

In [ ]:
Benzene_Subset = AirData[AirData["Name"] == "Outdoor Air Toxics - Benzene"].copy()